language: go
go:
  - 1.11.x
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install:
  - whereis google-chrome-stable
  - whereis chromedriver
  - go get -v .
  - go build
script:
  - ./podium https://talks.godoc.org/github.com/mmcloughlin/talks/bsp-demo-pearl/pearl.slide
