language: go
go:
  - 1.11.x
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install:
  - go get -v .
  - go build
before_script:
  - export PODIUM_CHROME_PATH="/usr/bin/google-chrome-stable"
  - export PODIUM_CHROME_DRIVER_PATH="/usr/lib/chromium-browser/chromedriver"
script:
  - ./podium https://talks.godoc.org/github.com/mmcloughlin/talks/bsp-demo-pearl/pearl.slide
